# -*- coding: utf-8 -*-
"""FaceColorExtractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXDZGugH16YtTgrbmAhj0dQxXcTlGdCn
"""

!wget -O face_landmarker.task -q https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task

!pip install mediapipe opencv-python
import mediapipe as mp
import numpy as np
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2
import os

SKIN_SAMPLE_POINTS = {
    "left_cheek": 50,
    "right_cheek": 280,
    "forehead": 151,
    "nose_bridge": 6,
    "chin": 175,
}

def get_landmarks(image_path):
    base_options = python.BaseOptions(model_asset_path="face_landmarker.task")
    options = vision.FaceLandmarkerOptions(
        base_options=base_options,
        num_faces=1
    )
    detector = vision.FaceLandmarker.create_from_options(options)

    image = cv2.imread(image_path)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB,
                         data=cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    result = detector.detect(mp_image)

    if not result.face_landmarks:
        return None, image

    h, w = image.shape[:2]
    landmarks = result.face_landmarks[0]  # first detected face
    points = [(int(lm.x * w), int(lm.y * h)) for lm in landmarks]

    return points, image

def visualize_point(image, points, index, color=(0, 255, 0)):
    x, y = points[index]
    cv2.circle(image, (x, y), 4, color, -1)
    cv2.putText(image, str(index), (x+5, y-5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.4, color, 1)

def sample_patch(image, center, patch_size=15):
    x, y = center
    half = patch_size // 2
    h, w = image.shape[:2]

    x1, x2 = max(0, x - half), min(w, x + half)
    y1, y2 = max(0, y - half), min(h, y + half)

    patch = image[y1:y2, x1:x2]
    return patch

def get_average_color(patch, color_space="LAB"):
    if color_space == "LAB":
        patch = cv2.cvtColor(patch, cv2.COLOR_BGR2LAB)

    # Flatten to a list of pixels and average
    pixels = patch.reshape(-1, 3)
    avg_color = np.mean(pixels, axis=0)
    return avg_color

def get_robust_skin_color(patch):
    lab = cv2.cvtColor(patch, cv2.COLOR_BGR2LAB)
    pixels = lab.reshape(-1, 3).astype(np.float32)

    # K-means to find dominant color cluster (handles shadows/highlights)
    from sklearn.cluster import KMeans
    kmeans = KMeans(n_clusters=2, n_init=10, random_state=42)
    labels = kmeans.fit_predict(pixels)

    # Take the larger cluster (assume it's the "true" skin tone, not shadow edge)
    counts = np.bincount(labels)
    dominant_cluster = np.argmax(counts)

    return kmeans.cluster_centers_[dominant_cluster]

def extract_skin_color(image_path):
    points, image = get_landmarks(image_path)
    if points is None:
        raise ValueError("No face detected")

    results = []
    for name, idx in SKIN_SAMPLE_POINTS.items():
        patch = sample_patch(image, points[idx], patch_size=15)
        if patch.size == 0:
            continue
        color = get_robust_skin_color(patch)
        results.append({
            "name": name,
            "index": idx,
            "pixel_coords": points[idx],
            "color_lab": color
        })

    return results

def find_color(image_path):

    if not os.path.exists(image_path):
        print(f"File not found: {image_path}")
        return

    # 1. Run landmark detection and save a visualization
    points, image = get_landmarks(image_path)
    if points is None:
        print("No face detected — try a clearer, front-facing photo")
        return

    print(f"Detected {len(points)} landmarks")

    # 2. Run the actual extraction — now a list of per-point results
    results = extract_skin_color(image_path)
    if not results:
        print("No valid patches sampled — check landmark indices / image size")
        return

    # 3. Convert each point's color back to RGB so it's human-readable
    for r in results:
        lab_patch = np.uint8([[r["color_lab"]]])  # 1x1 "image" for cvtColor
        rgb = cv2.cvtColor(lab_patch, cv2.COLOR_LAB2RGB)[0][0]
        r["color_rgb"] = rgb
        print(f"{r['name']} (idx {r['index']}) @ {r['pixel_coords']}: "
              f"LAB = {r['color_lab']}, RGB = {rgb}")